### ISSUE TITLE
vultr-cli: command not found

### ISSUE THREAD

**Issue by kp-emagine** [vultr/vultr-cli#34]
Compile the repo using `make build_linux_amd64`

"Export" my api key, per the repo instructions

Run: `vultr-cli server list` per the example, leads to the error message int he subject

**Comment by ddymko** [comment]
@kp-emagine 

Did you move the compiled binary to your `usr/local/bin` directory? If you didn't then you can't run the binary anywhere since it is not in your path.

The other way to run the binary after compiling it is by invoking it directly. Go into the same directory that the binary is in and run `./vultr-cli`

**Comment by ddymko** [comment]
Closing out this ticket due to inactivity.
