### ISSUE TITLE
Errors running `make` on go 1.10.1

### ISSUE THREAD

**Issue by dmitriz** [vultr/vultr-cli#37]
**Describe the bug**

Following the instructions from 
https://github.com/vultr/vultr-cli#building-from-source
I have cloned this repo and now getting errors running `make`:

```sh
→ make build_mac
building vultr-cli
env GOOS=darwin GOARCH=amd64 go build -gcflags=-trimpath=$GOPATH -o /Users/dmitrizaitsev/Repos/vultr-cli/builds/vultr-cli_darwin_amd64
main.go:17:8: cannot find package "github.com/vultr/vultr-cli/cmd" in any of:
	/usr/local/Cellar/go/1.10.1/libexec/src/github.com/vultr/vultr-cli/cmd (from $GOROOT)
	/Users/dmitrizaitsev/go/src/github.com/vultr/vultr-cli/cmd (from $GOPATH)
make: *** [_build] Error 1
```

**To Reproduce**

```sh
https://github.com/vultr/vultr-cli.git
cd vultr-cli
make build_mac
```

**Expected behavior**
Installing the CLI.

**Desktop (please complete the following information where applicable:**
 - OS: Mac OSX 10.8.5
 - Language Version 
```sh
→ go version
go version go1.10.1 darwin/amd64
→ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin12.6.0
Thread model: posix
```

**Comment by ddymko** [comment]
@dmitriz 

Thanks for creating a ticket. I am unable to recreate the issue on my end. 

Here is my console output:
```
➜  vultr-cli git:(master) make build_mac
building vultr-cli
env GOOS=darwin GOARCH=amd64 go build -gcflags=-trimpath=$GOPATH -o /Users/ddymko/Desktop/del/vultr-cli/builds/vultr-cli_darwin_amd64
built /Users/ddymko/Desktop/del/vultr-cli/builds/vultr-cli_darwin_amd64
➜  vultr-cli git:(master) go version
go version go1.12.7 darwin/amd64
➜  vultr-cli git:(master) gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
We are using go modules for this project and I noticed you are running on go 1.10 not sure if that may be causing issues on your end.

**Comment by dmitriz** [comment]
I have never used `go` myself. I have downloaded  the latest version 1.12.7 and followed installation instructions successfully, but could not detect any change in the path and calling `go` on my machine still runs the old version.

The page https://golang.org/doc/install suggests way of installing multiple versions but I was unable to follow them. If those instructions work correctly on your machine, maybe you could reproduce my errors running `make` along with go1.10.1, to see whether the error is caused by the older version or something else.

**Comment by ddymko** [comment]
@dmitriz 

I will take a deeper dive into what your exact issue may be.

For now you can download a precompiled release for mac os from:

https://github.com/vultr/vultr-cli/releases

or if you are running homebrew on your mac you can run the follow two commands

```
brew tap vultr/vultr-cli
brew install vultr-cli
```

**Comment by ddymko** [comment]
@dmitriz 

I noticed in your error that you are trying to build the go project outside of your `GOPATH`

`env GOOS=darwin ...  /Users/dmitrizaitsev/Repos/vultr-cli/builds/vultr-cli_darwin_amd64`

and since you are go `1.10.1` go is trying to look up your `GOPATH` for the source code

`/Users/dmitrizaitsev/go/src/github.com/vultr/vultr-cli/cmd (from $GOPATH)`

If you move the code to `/Users/dmitrizaitsev/Repos/vultr-cli/` over to `/Users/dmitrizaitsev/go/src/github.com/vultr/` This will resolve your issue.

This is replicated on my machine with go `1.10.7` by moving the code outside of my `gopath`. As of go `1.11.x` you could build outside of your gopath with gomodules
```
➜  vultr-cli git:(master) ✗ go1.10.7 version
go version go1.10.7 darwin/amd64
➜  vultr-cli git:(master) ✗ make build_mac
building vultr-cli
env GOOS=darwin GOARCH=amd64 go1.10.7 build -gcflags=-trimpath=$GOPATH -o /Users/ddymko/Desktop/vultr-cli/builds/vultr-cli_darwin_amd64
main.go:17:8: cannot find package "github.com/vultr/vultr-cli/cmd" in any of:
	/Users/ddymko/sdk/go1.10.7/src/github.com/vultr/vultr-cli/cmd (from $GOROOT)
	/Users/ddymko/go/src/github.com/vultr/vultr-cli/cmd (from $GOPATH)
make: *** [_build] Error 1
```

**Comment by dmitriz** [comment]
Thank you very much for your help! 

I have moved the project to the `go` subdirectory as you suggested and it had indeed solved some problems and allowed me to install `go1.11.12` (I still could not install `go1.12` on my OSX 10.8.5).

Also thanks for directing me to the precompiled release that I somehow missed earlier!

Not anymore critical for me, but that build error didn't go away even with 1.11.12:

```sh
→ go version
go version go1.11.12 darwin/amd64
→ make build_mac
building vultr-cli
env GOOS=darwin GOARCH=amd64 go build -gcflags=-trimpath=$GOPATH -o /Users/dmitrizaitsev/go/src/github.com/vultr/builds/vultr-cli_darwin_amd64
main.go:17:8: cannot find package "github.com/vultr/vultr-cli/cmd" in any of:
	/Users/dmitrizaitsev/go/src/github.com/vultr/vendor/github.com/vultr/vultr-cli/cmd (vendor tree)
	/Users/dmitrizaitsev/sdk/go1.11.12/src/github.com/vultr/vultr-cli/cmd (from $GOROOT)
	/Users/dmitrizaitsev/go/src/github.com/vultr/vultr-cli/cmd (from $GOPATH)
make: *** [Makefile:34: _build] Error 1
```

**Comment by ddymko** [comment]
Glad it helped a bit!

As for the issue of getting Go 1.12 on your macchine this is because your macOS version isn't supported. 
`Go 1.12 is the last release that will run on macOS 10.10 Yosemite. Go 1.13 will require macOS 10.11 El Capitan or later. `
https://golang.org/doc/go1.12#darwin

I will take a look into the build error some time today (If i have a chance).

**Comment by dmitriz** [comment]
> As for the issue of getting Go 1.12 on your macchine this is because your macOS version isn't supported.

Sometimes these versions still work, so I tried anyway :)
The problem with Go it still reports success but fails later on with cryptic messages that do not refer to the real cause - my OS version if that is the one.

Generally I have been having a rough ride with any Go software, where errors have always been hard to understand. :(

Still don't quite understand how the $GOPATH works, it is currently unset for me, maybe that is one of the problems?

**Comment by jakimfett** [comment]
> Still don't quite understand how the $GOPATH works...

You're in good company here.

Part of the difficulty is that the official docs do a [rather poor job](https://golang.org/cmd/go/#hdr-GOPATH_environment_variable) of explaining what, why, and how to set the various `$GO*` environmental variable bits.
Also, there seem to be a [couple](https://dave.cheney.net/2013/06/14/you-dont-need-to-set-goroot-really) of [gotchas](https://stackoverflow.com/questions/22877775/gopath-must-not-be-set-to-goroot-why-not).

StackOverflow [tries to explain](https://stackoverflow.com/questions/7970390/what-should-be-the-values-of-gopath-and-goroot/10847122#10847122) but the values/locations seem conditional on things poorly defined.

As best I can tell, `$GOROOT` is where `golang` is installed, and `$GOPATH` is where `golang` looks for the fiddly bits that make it...actually go.

Can someone knowledgeable correct my (our?) misconceptions?

**Comment by ddymko** [comment]
@jakimfett 

You are correct

`$GOROOT` is the location of your go installation

`$GOPATH` is where you could keep your compiled packages, executables, and source files.
Prior to `go 1.11` you were required to build your go applications within your `$GOPATH`. This is due to `go get || go install` storing the requires files and packages into go your `$GOPATH`

However, with the introduction of of `Gomodules` you can build your applications outside of your gopath. This is due to the ability to vendor packages now as opposed to needing requiring them in your `gopath`

Hopefully this can clear it up a bit:
- https://www.programming-books.io/essential/go/gopath-goroot-gobin-d6da4b8481f94757bae43be1fdfa9e73
- https://github.com/golang/go/wiki/Modules
- https://www.digitalocean.com/community/tutorials/understanding-the-gopath

I would also suggest joining the gopher slack. Really helpful
https://invite.slack.golangbridge.org/

**Comment by geek1011** [comment]
Also, you can use modules in your GOPATH by either using Go 1.13+ or setting GO111MODULE=true.
