### ISSUE TITLE
[Enhancement] - os flag seems to take precedence over app flag when creating server

### ISSUE THREAD

**Issue by rohankrishnadev** [vultr/vultr-cli#84]
**Describe the bug**
I'm trying to create a server with Docker installed. In the WebUI I can choose between Ubuntu 18.04 and CentOS 7. When I try to create a server with CLI, it looks like I can pass any value to the os flag and that takes precedence over the app flag.

**To Reproduce**
1. $vultr-cli server create --app 37 --plan 201 --region 40 --os 367
2. This create a Fedora 31 x64 server
3. Docker isn't installed on the server, this is expected as it isn't supported

**Expected behavior**
When app flag is passed then vultr-cli should restrict OSID to be the ones that are supported or user 186 as the default.
For the above command I should be restricted to using OSID of 167, 381, 270 or 186.

**Screenshots**
N/A

**Desktop (please complete the following information where applicable:**
 - OS: macOS Catalina 10.15.3
 - Version: Vultr-cli v0.2.1

**Additional context**

N/A

**Comment by ddymko** [comment]
Hey @rohankrishnadev 

Thanks for creating the ticket. Like you said the OSID takes precedence over any other param this is how the API is designed. You will get similar behavior using the API directly since the OSID gets read in 1st and executes accordingly from there.

I will change this from a `bug` to an `enhancement` since the behavior in the CLI can be improved upon

**Comment by rohankrishnadev** [comment]
@ddymko Thanks! That'd be great.
